am: 76915d0 - libweave: Fix build break on Brillo
The private member |currently_online_| is no longer used and causes
the following error on Android/Brillo builds:

external/libweave/src/privet/wifi_bootstrap_manager.h:109:8:
error: private field 'currently_online_' is not used [-Werror,-Wunused-private-field]

Remove the field to fix the compile break.

Change-Id: I0830a4d12f777956638a12514565bb2270680e34